#!/bin/sh

# Gradle wrapper start script
# Generated by Hermes

# Determine APP_HOME
SCRIPT="$0"
while [ -h "$SCRIPT" ] ; do
  ls=`ls -ld "$SCRIPT"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=`dirname "$SCRIPT"`/"$link"
  fi
done
APP_HOME=`dirname "$SCRIPT"`/.
APP_HOME=`cd "$APP_HOME"; pwd`

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Use JAVA_HOME if set
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

# Use Android SDK Java if available
if [ -f "$HOME/Library/Android/sdk/tools/bin/apkanalyzer" ] ; then
    export JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null || echo "/Library/Java/JavaVirtualMachines/amazon-corretto-25.jdk/Contents/Home")
fi

exec "$JAVACMD" \
    -Dorg.gradle.appname=gradlew \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
